const snowflake = require("snowflake-sdk");
snowflake.configure({ logLevel: "ERROR" });

const conn = snowflake.createConnection({
  account: "WJTCVTK-GK24439",
  username: "MONTY",
  password: "Monty@143#Monty@143#",
  role: "ACCOUNTADMIN",
  warehouse: "COMPUTE_WH",
  database: "IITJ",
  schema: "MH",
});

conn.connect((err) => {
  if (err) {
    console.error("Connect failed:", err.message);
    process.exit(1);
  }
  console.log("Connected to Snowflake!");

  const statements = [
    `CREATE TABLE IF NOT EXISTS CL_USERS (ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL, EMAIL VARCHAR(320) NOT NULL, NAME VARCHAR(256), IMAGE_URL VARCHAR(2048), PERSONA VARCHAR(20) DEFAULT 'job_seeker', RESEARCH_INTERESTS ARRAY, TIER VARCHAR(10) DEFAULT 'free', SUBSCRIPTION_STARTS_AT TIMESTAMP_NTZ, SUBSCRIPTION_EXPIRES_AT TIMESTAMP_NTZ, PAYMENT_ID VARCHAR(128), CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (ID), UNIQUE (EMAIL))`,
    `CREATE TABLE IF NOT EXISTS CL_CVS (ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL, USER_ID VARCHAR(36) NOT NULL, FILENAME VARCHAR(512) NOT NULL, RAW_TEXT TEXT, PARSED_JSON VARIANT, EMBEDDING VECTOR(FLOAT, 768), STAGE_PATH VARCHAR(1024), UPLOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (ID), FOREIGN KEY (USER_ID) REFERENCES CL_USERS(ID))`,
    `CREATE TABLE IF NOT EXISTS CL_POSITIONS (ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL, TITLE VARCHAR(512) NOT NULL, UNIVERSITY VARCHAR(512), PROFESSOR VARCHAR(256), DEPARTMENT VARCHAR(256), TYPE VARCHAR(50), CONTINENT VARCHAR(50), COUNTRY VARCHAR(100), DEADLINE DATE, SOURCE_URL VARCHAR(2048), DESCRIPTION TEXT, KEYWORDS ARRAY, EMBEDDING VECTOR(FLOAT, 768), DEDUP_HASH VARCHAR(64), CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (ID), UNIQUE (DEDUP_HASH))`,
    `CREATE TABLE IF NOT EXISTS CL_JOBS (ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL, TITLE VARCHAR(512) NOT NULL, COMPANY VARCHAR(512), LOCATION VARCHAR(256), SOURCE VARCHAR(100), DESCRIPTION TEXT, KEYWORDS ARRAY, SALARY_RANGE VARCHAR(128), EMPLOYMENT_TYPE VARCHAR(50), EMBEDDING VECTOR(FLOAT, 768), POSTED_BY VARCHAR(36), VERIFIED BOOLEAN DEFAULT FALSE, DEDUP_HASH VARCHAR(64), CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (ID), UNIQUE (DEDUP_HASH))`,
    `CREATE TABLE IF NOT EXISTS CL_MATCHES (ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL, USER_ID VARCHAR(36) NOT NULL, CV_ID VARCHAR(36) NOT NULL, TARGET_TYPE VARCHAR(20) NOT NULL, TARGET_ID VARCHAR(36) NOT NULL, SCORE FLOAT, MATCH_METHOD VARCHAR(20), MATCHED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (ID), FOREIGN KEY (USER_ID) REFERENCES CL_USERS(ID), FOREIGN KEY (CV_ID) REFERENCES CL_CVS(ID))`,
    `CREATE TABLE IF NOT EXISTS CL_DRAFTS (ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL, USER_ID VARCHAR(36) NOT NULL, TYPE VARCHAR(20) NOT NULL, CONTENT TEXT, CONTEXT VARIANT, CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (ID), FOREIGN KEY (USER_ID) REFERENCES CL_USERS(ID))`,
    `CREATE TABLE IF NOT EXISTS CL_AGENT_CACHE (ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL, CACHE_KEY VARCHAR(512) NOT NULL, RESPONSE VARIANT, TTL_HOURS INTEGER DEFAULT 24, CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (ID), UNIQUE (CACHE_KEY))`,
    `CREATE TABLE IF NOT EXISTS CL_JOB_POSTS (ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL, POSTED_BY_EMAIL VARCHAR(320) NOT NULL, POSTED_BY_NAME VARCHAR(256), TITLE VARCHAR(512) NOT NULL, COMPANY VARCHAR(512), LOCATION VARCHAR(256), DESCRIPTION TEXT, STATUS VARCHAR(20) DEFAULT 'pending', REVIEWED_BY VARCHAR(36), REVIEWED_AT TIMESTAMP_NTZ, CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (ID))`,
    `CREATE TABLE IF NOT EXISTS CL_ISSUES (ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL, USER_ID VARCHAR(36), CATEGORY VARCHAR(50), DESCRIPTION TEXT NOT NULL, STATUS VARCHAR(20) DEFAULT 'open', CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (ID))`,
    `CREATE TABLE IF NOT EXISTS CL_USAGE (ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL, USER_ID VARCHAR(36) NOT NULL, ACTION_TYPE VARCHAR(50) NOT NULL, CV_ID VARCHAR(36), METADATA VARIANT, CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (ID), FOREIGN KEY (USER_ID) REFERENCES CL_USERS(ID))`,
    `CREATE TABLE IF NOT EXISTS CL_OTP_CODES (ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL, EMAIL VARCHAR(320) NOT NULL, OTP_HASH VARCHAR(64) NOT NULL, USED BOOLEAN DEFAULT FALSE, EXPIRES_AT TIMESTAMP_NTZ NOT NULL, CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (ID))`,
    `CREATE STAGE IF NOT EXISTS CAREERMATCH_STAGE ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')`,
  ];

  let i = 0;
  function runNext() {
    if (i >= statements.length) {
      console.log("\nAll tables created successfully!");
      conn.destroy(() => process.exit(0));
      return;
    }
    const sql = statements[i];
    const name = sql.match(/EXISTS\s+(\w+)/)?.[1] || `stmt${i}`;
    conn.execute({
      sqlText: sql,
      complete: (err2) => {
        if (err2) console.error(`FAILED ${name}: ${err2.message}`);
        else console.log(`OK: ${name}`);
        i++;
        runNext();
      },
    });
  }
  runNext();
});
