-- CareerMatch Snowflake DDL (reference only — auto-created at runtime by utils/snowflake_utils.py)

-- Stage for CV file storage
CREATE STAGE IF NOT EXISTS IITJ.MH.CAREERMATCH_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- Users table
CREATE TABLE IF NOT EXISTS IITJ.MH.CM_USERS (
    USER_ID       NUMBER AUTOINCREMENT PRIMARY KEY,
    EMAIL         VARCHAR NOT NULL UNIQUE,
    DISPLAY_NAME  VARCHAR,
    PERSONA       VARCHAR,       -- 'Student' or 'Job Seeker'
    GOOGLE_SUB    VARCHAR,       -- Google OAuth subject ID
    CREATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- CVs table
CREATE TABLE IF NOT EXISTS IITJ.MH.CM_CVS (
    CV_ID         NUMBER AUTOINCREMENT PRIMARY KEY,
    USER_ID       NUMBER NOT NULL REFERENCES IITJ.MH.CM_USERS(USER_ID),
    CV_FILE_PATH  VARCHAR NOT NULL,     -- stage-relative path
    PARSED_JSON   VARIANT,              -- structured extraction from CV
    UPLOADED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- University positions (cached from Perplexity deep research)
CREATE TABLE IF NOT EXISTS IITJ.MH.CM_POSITIONS (
    POS_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    TITLE           VARCHAR,
    UNIVERSITY      VARCHAR,
    COUNTRY         VARCHAR,
    CONTINENT       VARCHAR,
    POSITION_TYPE   VARCHAR,       -- Masters / PhD / Postdoc
    DEADLINE        DATE,
    DESCRIPTION     VARCHAR(16777216),
    REQUIREMENTS    VARCHAR(16777216),
    PROFESSOR_NAME  VARCHAR,
    PROFESSOR_EMAIL VARCHAR,
    SOURCE_URL      VARCHAR,
    EMBEDDING       VECTOR(FLOAT, 768),   -- Cortex EMBED_TEXT output
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Job listings (cached from Perplexity deep research)
CREATE TABLE IF NOT EXISTS IITJ.MH.CM_JOBS (
    JOB_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    TITLE           VARCHAR,
    COMPANY         VARCHAR,
    LOCATION        VARCHAR,
    DESCRIPTION     VARCHAR(16777216),
    REQUIRED_SKILLS VARCHAR(16777216),
    EXPERIENCE_LEVEL VARCHAR,
    SALARY_RANGE    VARCHAR,
    SOURCE_URL      VARCHAR,
    EMBEDDING       VECTOR(FLOAT, 768),
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Match history
CREATE TABLE IF NOT EXISTS IITJ.MH.CM_MATCHES (
    MATCH_ID        NUMBER AUTOINCREMENT PRIMARY KEY,
    USER_ID         NUMBER NOT NULL REFERENCES IITJ.MH.CM_USERS(USER_ID),
    CV_ID           NUMBER NOT NULL REFERENCES IITJ.MH.CM_CVS(CV_ID),
    TARGET_TYPE     VARCHAR,       -- 'position' or 'job'
    TARGET_ID       NUMBER,        -- POS_ID or JOB_ID
    SIMILARITY_SCORE FLOAT,
    MISSING_SKILLS  VARCHAR(16777216),
    MATCHED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- SOP / email drafts
CREATE TABLE IF NOT EXISTS IITJ.MH.CM_DRAFTS (
    DRAFT_ID      NUMBER AUTOINCREMENT PRIMARY KEY,
    USER_ID       NUMBER NOT NULL REFERENCES IITJ.MH.CM_USERS(USER_ID),
    MATCH_ID      NUMBER REFERENCES IITJ.MH.CM_MATCHES(MATCH_ID),
    DRAFT_TYPE    VARCHAR,       -- 'SOP' or 'Email'
    CONTENT       VARCHAR(16777216),
    CREATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Agent cache (avoid redundant Perplexity calls)
CREATE TABLE IF NOT EXISTS IITJ.MH.CM_AGENT_CACHE (
    CACHE_ID      NUMBER AUTOINCREMENT PRIMARY KEY,
    AGENT_NAME    VARCHAR,
    QUERY_HASH    VARCHAR,
    RESPONSE      VARCHAR(16777216),
    CREATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EXPIRES_AT    TIMESTAMP_NTZ
);

-- Search optimization for frequent cache/filter lookups
ALTER TABLE IITJ.MH.CM_AGENT_CACHE
    ADD SEARCH OPTIMIZATION ON EQUALITY(AGENT_NAME, QUERY_HASH);

ALTER TABLE IITJ.MH.CM_POSITIONS
    ADD SEARCH OPTIMIZATION ON EQUALITY(POSITION_TYPE, CONTINENT, TITLE, UNIVERSITY);

ALTER TABLE IITJ.MH.CM_JOBS
    ADD SEARCH OPTIMIZATION ON EQUALITY(TITLE, COMPANY);

-- Optional scheduled cleanup (enable in production account as needed)
CREATE OR REPLACE TASK IITJ.MH.CM_AGENT_CACHE_CLEANUP
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 0 */6 * * * UTC'
AS
DELETE FROM IITJ.MH.CM_AGENT_CACHE
WHERE EXPIRES_AT IS NOT NULL
  AND EXPIRES_AT < CURRENT_TIMESTAMP();